自動更新機能の実装
shotafukushi/chat-space pull request #6
Opened 2019-03-30 12:47 UTC by shotafukushi

確認していただきたい箇所を以下に記述いたします。
1. 2画面同時に開き、適切に自動更新されるか
2. 自動更新時に、画面が最下部までスクロールされるか
以下、自動更新のgifです
https://gyazo.com/56aac6c23662f02b27d3dcb1c0b784cf

2019-03-30 12:48 UTC, TOMARUMARU commented on app/views/messages/create.json.jbuilder
>  json.image              @message.image.url
こちらのファイルちょいちょい被ってる記述がありますね

2019-03-31 06:02 UTC, ghost requested changes

2019-03-31 06:02 UTC, hiroki5123 commented on app/assets/javascripts/messages.js
> +      window.alert("文字を入力してください");
alert("文字を入力してください");
でwindowなしでいけませんか？

2019-03-31 06:20 UTC, kuroko918 commented on app/assets/javascripts/messages.js
> +  $(function(){
1行目と被っているので、ここは消しておきましょう！
ぜひこの意味も調べてみましょう！

2019-03-31 06:20 UTC, kuroko918 commented on app/assets/javascripts/messages.js
>      return false;
この記述は必要ですか？

2019-03-31 06:20 UTC, kuroko918 commented on app/views/messages/create.json.jbuilder
> +json.content_present    @message.content.present?
こちらは使っていますか？

2019-03-31 06:20 UTC, kuroko918 commented on app/views/messages/create.json.jbuilder
> +json.image_present      @message.image.present?
こちらは使っていますか？

2019-03-31 07:29 UTC, kuroko918 commented on app/views/messages/create.json.jbuilder
> +json.image_present      @message.image.present?
こちらは如何でしょうか？

2019-03-31 07:29 UTC, kuroko918 commented
image_presentについては如何でしょうか？

2019-03-31 07:35 UTC, shotafukushi commented
image_present消し忘れです。すみません。

2019-03-31 07:41 UTC, kuroko918 commented
いいかと思います！
LGTMです！

2019-03-31 07:45 UTC, merged